name: Bug Report
description: Report something that doesn't seem to work correct
title: '[Bug]'
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Describe what exactly is going wrong
      placeholder: Shorts tab on channels don't work
    validations:
      required: true
  - type: markdown
    attributes:
      value: '# Free space, enter your comments here'
  - type: textarea
    attributes:
      label: Notes
