name: Bug Report
description: Report something that doesn't seem to work correct
title: '[Bug]'
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Describe what happened
      description: Describe how you managed to get the error as detailed as you can
      placeholder: Shorts tab on channels don't work
    validations:
      required: true
  - type: input
    attributes:
      label: Instance URL
      description: The instance this error occured at
      placeholder: https://tube.kuylar.dev
  - type: input
    attributes:
      label: LightTube version
      placeholder: 2023.01.21 / 1.0.9.0
    validations:
      required: true
  - type: input
    attributes:
      label: Resource path
      placeholder: https://tube.kuylar.dev/watch?v=dQw4w9WgXcQ
    validations:
      required: true
  - type: markdown
    attributes:
      value: '# Free space, enter your comments here'
  - type: textarea
    attributes:
      label: Notes
