name: Bug Report
description: Report an error that you just encountered
title: '[Bug]'
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Describe what happened
      description: Describe how you managed to get the error as detailed as you can
      placeholder: Shorts tab on channels don't work
    validations:
      required: true
  - type: markdown
    attributes:
      value: '# There are some fields in the error page. Fill those values here'
  - type: input
    attributes:
      label: Instance URL
      description: The instance this error occured at
      placeholder: https://tube.kuylar.dev
  - type: input
    attributes:
      label: LightTube & InnerTube versions
      placeholder: 2023.01.21 / 1.0.9.0
    validations:
      required: true
  - type: input
    attributes:
      label: Resource path
      placeholder: https://tube.kuylar.dev/watch?v=dQw4w9WgXcQ
    validations:
      required: true
  - type: input
    attributes:
      label: Language & region
      placeholder: en_US
    validations:
      required: true
  - type: textarea
    attributes:
      label: Stack trace
      description: The following text (the whole thing)
    validations:
      required: true
  - type: markdown
    attributes:
      value: '# Free space, enter your comments here'
  - type: textarea
    attributes:
      label: Notes
